# W.R.A.P. 3 CMS engine configuration.

# Provides /usr/share/wrap3-cms/ engine through /wrap/ alias.
# Activate with
#   a2enconf wrap3-cms
# and add directory index rule to your site config, e.g.:
#   DirectoryIndex index.html index.php /wrap/wrap.php

Alias /wrap/ /usr/share/wrap3-cms/

<Directory /usr/share/wrap3-cms/>
    Require all granted
    AllowOverride All
</Directory>
