# Default Apache2 site for the W.R.A.P. 3 CMS.

# This is the base for the actual content structure, the CMS
# engine is provided from /usr/share/wrap3-cms/ through /wrap/
# alias rule.

<VirtualHost *:80>
    ServerName wrap3.localhost
    DocumentRoot /var/lib/wrap3/www
    DirectoryIndex index.html index.php /wrap/wrap.php

    <Directory /var/lib/wrap3/www>
        Require all granted
        AllowOverride All
    </Directory>
</VirtualHost>
